#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
  CREATE USER "${APPLICATION_DB_USERNAME}" WITH PASSWORD '${APPLICATION_DB_PASSWORD}' SUPERUSER;
  CREATE DATABASE "${APPLICATION_DB}" WITH OWNER "${APPLICATION_DB_USERNAME}";
  GRANT ALL PRIVILEGES ON DATABASE "${APPLICATION_DB}" TO "${APPLICATION_DB_USERNAME}";
EOSQL
